pipeline {
	agent {
		node {
			label 'maven' 
		}
	}
	options {
		timeout(time: 20, unit: 'MINUTES') 
	}
	stages {
		stage('preamble') {
			steps {
				script {
					echo "Hello world"
					openshift.withCluster() {
						openshift.withProject() {
							echo "Using project: ${openshift.project()}"
						}
					}
				}
			}
		}
		stage('extract template') {
			steps {
				script {
					echo "Hello world"
					openshift.withCluster() {
						openshift.withProject() {
							sh "./promote-application.sh"
						}
					}
				}
			}
		}
	}
}

 	